# Generated by Django 6.0.4 on 2026-05-14 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('short', 'Short'), ('detailed', 'Detailed')], max_length=50)),
                ('content', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('important_questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='notes.uploadednote')),
            ],
        ),
    ]
