# Generated by Django 6.0.4 on 2026-05-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadednote',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of user-defined tags'),
        ),
    ]
